### ISSUE TITLE
ARG commands - clustering

### ISSUE THREAD

**Issue by ghost** [splunk/docker-splunk-legacy#79]
Hello,

  I have been trying to enable clustering through compose file with no joy.

Could someone shed some light to the secret sauce?

 ```
splunkmaster:
    restart: always
    build: ./splunkmaster
    hostname: splunkmaster
    # image: splunk/splunk:6.5.3
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_CMD_1: splunk edit cluster-config -mode master -replication_factor 3 -search_factor 2 -secret newsecret123456 -cluster_label cluster1 auth admin:changeme
      SPLUNK_CMD_2: splunk restart


```
