### ISSUE TITLE
DeamonSet Logs : asking to set the password 

### ISSUE THREAD

**Issue by sharmmoh1983** [splunk/docker-splunk-legacy#91]
I bit confused , daemonset was running fine for splunk UF till yesterday but now it logs are showing:
Please enter a new password

**Comment by sharmmoh1983** [comment]
```
env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license --answer-yes --seed-passwd --changeme"
        - name: SPLUNK_USER
```
